apiVersion: v1
kind: Namespace
metadata:
  name:  linkerd1
  annotations: 
    linkerd.io/inject: enabled

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api2
  namespace: linkerd1
spec:
  selector:
    matchLabels:
      app: api2
  template:
    metadata:
      labels:
        app: api2
    spec:
      containers:
      - name: api2
        image: verifylinkerd.azurecr.io/api2:latest
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: api2service
  namespace: linkerd1
spec:
  type: LoadBalancer
  selector:
    app: api2
  ports:
  - port: 80
    targetPort: 80


